### ISSUE TITLE
Updated to current master and lost functionality

### ISSUE THREAD

**Issue by ravl1084** [vim-pandoc/vim-pandoc#263] opened 2018-03-28 15:24 UTC
I just updated to current master from this repo and now running `:Pandoc pdf` produces no output, there is no error message, also no incantation logged under `:messages`.

I'm using Ubuntu 16.04, pandoc 2.1.2.

**Comment by adikari** [comment] 2018-04-03 05:27
Same here. I have tried both in centos and osx.

**Comment by maccius** [comment] 2018-04-15 23:37
The plugin now requires Python 3.  I had a similar problem to yours, and once I reconfigured my environment, it all worked well again.

**Comment by ravl1084** [comment] 2018-04-16 13:31
I have both Python 3 and 2.7 installed. What do you mean by 'reconfigured my environment'?

**Comment by fmoralesc** [comment] 2018-04-16 13:58
@ravl1084 Is your vim version using python2 or 3?

**Comment by fmoralesc** [comment] 2019-05-05 10:25
This seems to have been a duplicate of the issue where the python interpreter tries to use outdated .pyc files. It should be fixed by reinstalling the plugin, or by removing all existing .pyc files in the plugin directory.

**Closed by fmoralesc** 2019-05-05 10:25 UTC
