### ISSUE TITLE
:Pandoc pdf fail on MacVim in Yosemite

### ISSUE THREAD

**Issue by zaript** [vim-pandoc/vim-pandoc#133] opened 2015-06-09 14:24 UTC
This might be related to: https://github.com/vim-pandoc/vim-pandoc/issues/121
The issue does not specify workaround, and I didn't find it myself yet.

~~~
Error detected while processing function pandoc#command#Pandoc:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/zaript/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 78, in <module>
    class PandocHelpParser(object):
  File "/Users/zaript/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 115, in PandocHelpParser
    @wrap_formats
  File "/Users/zaript/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 75, in wrap_formats
    data = fn()
  File "/Users/zaript/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 117, in _get_output_formats
    return get_raw_pandoc_data("Output formats:(.*)\[\*for pdf")
  File "/Users/zaript/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 67, in get_raw_pandoc_data
    return re.search(pattern, data, re.DOTALL).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
line    5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'pandoc' is not defined   
~~~

**Comment by nasenatmer** [comment] 2015-06-09 15:47
I get the same error here on an up-to-date Arch Linux machine:

```vim
Error detected while processing function pandoc#command#Pandoc:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jakob/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 78, in <mo
dule>
    class PandocHelpParser(object):
  File "/home/jakob/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 115, in Pa
ndocHelpParser
    @wrap_formats
  File "/home/jakob/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 75, in wra
p_formats
    data = fn()
  File "/home/jakob/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 117, in _g
et_output_formats
    return get_raw_pandoc_data("Output formats:(.*)\[\*for pdf")
  File "/home/jakob/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 67, in get
_raw_pandoc_data
    return re.search(pattern, data, re.DOTALL).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
line    5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'pandoc' is not defined
```

**Comment by INstinct42** [comment] 2015-06-09 15:55
I have the same error on OS X Yosemite 10.10.3 with newest MacVim from Homebrew.

```vim
Error detected while processing function pandoc#command#Pandoc:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jonas/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 78, in <module>
    class PandocHelpParser(object):
  File "/Users/jonas/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 115, in PandocHelpParser
    @wrap_formats
  File "/Users/jonas/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 75, in wrap_formats
    data = fn()
  File "/Users/jonas/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 117, in _get_output_formats
    return get_raw_pandoc_data("Output formats:(.*)\[\*for pdf")
  File "/Users/jonas/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 67, in get_raw_pandoc_data
    return re.search(pattern, data, re.DOTALL).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
line    5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'pandoc' is not defined
Press ENTER or type command to continue
```

```bash
~ $ brew info macvim                                              
macvim: stable 7.4-76, HEAD
A GUI for vim, made for OS X
https://code.google.com/p/macvim/
/usr/local/Cellar/macvim/7.4-76 (1903 files, 36M)
  Built from source with: --override-system-vim
/usr/local/Cellar/macvim/HEAD (1902 files, 34M) *
  Built from source with: --with-lua 
...
```

(Worked fine just a few days ago...)

**Comment by fmoralesc** [comment] 2015-06-09 16:02
This is a regression from 7ffb061d283e9cbc20bf47f008370e1e6a135686. If you can please provide the messages shown if you change the `get_raw_pandoc_data()` function in `pythonx/vim_pandoc/command.py` to this:
~~~ python
def get_raw_pandoc_data(pattern):
    data = str(Popen(["pandoc", "--help"], stdout=PIPE).communicate()[0])
    print data
    reply = re.search(pattern, data, re.DOTALL).group(1)
    print reply
    return reply
~~~
I can't reproduce at the moment, so it would be really helpful.

**Comment by INstinct42** [comment] 2015-06-09 16:12
Output of `:Pandoc pdf` in MacVim after I applied the changes to `get_raw_pandoc_data(pattern)`:

```vim
pandoc [OPTIONS] [FILES]
Input formats:  commonmark, docbook, docx, epub, haddock, html, json*, latex,
                markdown, markdown_github, markdown_mmd, markdown_phpextra,
                markdown_strict, mediawiki, native, opml, org, rst, t2t,
                textile, twiki
                [ *only Pandoc's JSON version of native AST]
Output formats: asciidoc, beamer, commonmark, context, docbook, docx, dokuwiki,
                dzslides, epub, epub3, fb2, haddock, html, html5, icml, json*,
                latex, man, markdown, markdown_github, markdown_mmd,
                markdown_phpextra, markdown_strict, mediawiki, native, odt,
                opendocument, opml, org, pdf**, plain, revealjs, rst, rtf, s5,
                slideous, slidy, texinfo, textile
                [**for pdf output, use latex or beamer and -o FILENAME.pdf]
Options:
  -f FORMAT, -r FORMAT  --from=FORMAT, --read=FORMAT
  -t FORMAT, -w FORMAT  --to=FORMAT, --write=FORMAT
  -o FILENAME           --output=FILENAME
                        --data-dir=DIRECTORY
                        --strict
  -R                    --parse-raw
  -S                    --smart
                        --old-dashes
                        --base-header-level=NUMBER
                        --indented-code-classes=STRING
  -F PROGRAM            --filter=PROGRAM
                        --normalize
  -p                    --preserve-tabs
                        --tab-stop=NUMBER
                        --track-changes=accept|reject|all
                        --extract-media=PATH
  -s                    --standalone
                        --template=FILENAME
  -M KEY[:VALUE]        --metadata=KEY[:VALUE]
  -V KEY[:VALUE]        --variable=KEY[:VALUE]
  -D FORMAT             --print-default-template=FORMAT
                        --print-default-data-file=FILE
                        --no-wrap
                        --columns=NUMBER
                        --toc, --table-of-contents
                        --toc-depth=NUMBER
                        --no-highlight
                        --highlight-style=STYLE
  -H FILENAME           --include-in-header=FILENAME
  -B FILENAME           --include-before-body=FILENAME
  -A FILENAME           --include-after-body=FILENAME
                        --self-contained
                        --offline
  -5                    --html5
                        --html-q-tags
                        --ascii
                        --reference-links
                        --atx-headers
                        --chapters
  -N                    --number-sections
                        --number-offset=NUMBERS
                        --no-tex-ligatures
                        --listings
  -i                    --incremental
                        --slide-level=NUMBER
                        --section-divs
                        --default-image-extension=extension
                        --email-obfuscation=none|javascript|references
                        --id-prefix=STRING
  -T STRING             --title-prefix=STRING
  -c URL                --css=URL
                        --reference-odt=FILENAME
                        --reference-docx=FILENAME
                        --epub-stylesheet=FILENAME
                        --epub-cover-image=FILENAME
                        --epub-metadata=FILENAME
                        --epub-embed-font=FILE
                        --epub-chapter-level=NUMBER
                        --latex-engine=PROGRAM
                        --latex-engine-opt=STRING
                        --bibliography=FILE
                        --csl=FILE
                        --citation-abbreviations=FILE
                        --natbib
                        --biblatex
  -m[URL]               --latexmathml[=URL], --asciimathml[=URL]
                        --mathml[=URL]
                        --mimetex[=URL]
                        --webtex[=URL]
                        --jsmath[=URL]
                        --mathjax[=URL]
                        --katex[=URL]
                        --katex-stylesheet=URL
                        --gladtex
                        --trace
                        --dump-args
                        --ignore-args
                        --verbose
  -v                    --version
  -h                    --help
  commonmark, docbook, docx, epub, haddock, html, json*, latex,
                markdown, markdown_github, markdown_mmd, markdown_phpextra,
                markdown_strict, mediawiki, native, opml, org, rst, t2t,
                textile, twiki
                [ *only Pandoc's JSON version of native AST]
pandoc [OPTIONS] [FILES]
Input formats:  commonmark, docbook, docx, epub, haddock, html, json*, latex,
                markdown, markdown_github, markdown_mmd, markdown_phpextra,
                markdown_strict, mediawiki, native, opml, org, rst, t2t,
                textile, twiki
                [ *only Pandoc's JSON version of native AST]
Output formats: asciidoc, beamer, commonmark, context, docbook, docx, dokuwiki,
                dzslides, epub, epub3, fb2, haddock, html, html5, icml, json*,
                latex, man, markdown, markdown_github, markdown_mmd,
                markdown_phpextra, markdown_strict, mediawiki, native, odt,
                opendocument, opml, org, pdf**, plain, revealjs, rst, rtf, s5,
                slideous, slidy, texinfo, textile
                [**for pdf output, use latex or beamer and -o FILENAME.pdf]
Options:
  -f FORMAT, -r FORMAT  --from=FORMAT, --read=FORMAT
  -t FORMAT, -w FORMAT  --to=FORMAT, --write=FORMAT
  -o FILENAME           --output=FILENAME
                        --data-dir=DIRECTORY
                        --strict
  -R                    --parse-raw
  -S                    --smart
                        --old-dashes
                        --base-header-level=NUMBER
                        --indented-code-classes=STRING
  -F PROGRAM            --filter=PROGRAM
                        --normalize
  -p                    --preserve-tabs
                        --tab-stop=NUMBER
                        --track-changes=accept|reject|all
                        --extract-media=PATH
  -s                    --standalone
                        --template=FILENAME
  -M KEY[:VALUE]        --metadata=KEY[:VALUE]
  -V KEY[:VALUE]        --variable=KEY[:VALUE]
  -D FORMAT             --print-default-template=FORMAT
                        --print-default-data-file=FILE
                        --no-wrap
                        --columns=NUMBER
                        --toc, --table-of-contents
                        --toc-depth=NUMBER
                        --no-highlight
                        --highlight-style=STYLE
  -H FILENAME           --include-in-header=FILENAME
  -B FILENAME           --include-before-body=FILENAME
  -A FILENAME           --include-after-body=FILENAME
                        --self-contained
                        --offline
  -5                    --html5
                        --html-q-tags
                        --ascii
                        --reference-links
                        --atx-headers
                        --chapters
  -N                    --number-sections
                        --number-offset=NUMBERS
                        --no-tex-ligatures
                        --listings
  -i                    --incremental
                        --slide-level=NUMBER
                        --section-divs
                        --default-image-extension=extension
                        --email-obfuscation=none|javascript|references
                        --id-prefix=STRING
  -T STRING             --title-prefix=STRING
  -c URL                --css=URL
                        --reference-odt=FILENAME
                        --reference-docx=FILENAME
                        --epub-stylesheet=FILENAME
                        --epub-cover-image=FILENAME
                        --epub-metadata=FILENAME
                        --epub-embed-font=FILE
                        --epub-chapter-level=NUMBER
                        --latex-engine=PROGRAM
                        --latex-engine-opt=STRING
                        --bibliography=FILE
                        --csl=FILE
                        --citation-abbreviations=FILE
                        --natbib
                        --biblatex
  -m[URL]               --latexmathml[=URL], --asciimathml[=URL]
                        --mathml[=URL]
                        --mimetex[=URL]
                        --webtex[=URL]
                        --jsmath[=URL]
                        --mathjax[=URL]
                        --katex[=URL]
                        --katex-stylesheet=URL
                        --gladtex
                        --trace
                        --dump-args
                        --ignore-args
                        --verbose
  -v                    --version
  -h                    --help
Error detected while processing function pandoc#command#Pandoc:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jonas/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 81, in <module>
    class PandocHelpParser(object):
  File "/Users/jonas/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 118, in PandocHelpParser
    @wrap_formats
  File "/Users/jonas/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 78, in wrap_formats
    data = fn()
  File "/Users/jonas/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 120, in _get_output_formats
    return get_raw_pandoc_data("Output formats:(.*)\[\*for pdf")
  File "/Users/jonas/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py", line 68, in get_raw_pandoc_data
    reply = re.search(pattern, data, re.DOTALL).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
line    5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'pandoc' is not defined
```

**Comment by fmoralesc** [comment] 2015-06-09 16:20
Thanks a lot! I get what the issue is now, will see how I'll fix it.

**Comment by fmoralesc** [comment] 2015-06-09 16:20
Can you tell me which pandoc version is that?

**Comment by INstinct42** [comment] 2015-06-09 16:21
```bash
~ $ pandoc --version                                              
pandoc 1.14.0.4
Compiled with texmath 0.8.2, highlighting-kate 0.6.
Syntax highlighting is supported for the following languages:
    abc, actionscript, ada, agda, apache, asn1, asp, awk, bash, bibtex, boo, c,
    changelog, clojure, cmake, coffee, coldfusion, commonlisp, cpp, cs, css,
    curry, d, diff, djangotemplate, dockerfile, dot, doxygen, doxygenlua, dtd,
    eiffel, email, erlang, fasm, fortran, fsharp, gcc, glsl, gnuassembler, go,
    haskell, haxe, html, idris, ini, isocpp, java, javadoc, javascript, json,
    jsp, julia, kotlin, latex, lex, lilypond, literatecurry, literatehaskell,
    lua, m4, makefile, mandoc, markdown, mathematica, matlab, maxima, mediawiki,
    metafont, mips, modelines, modula2, modula3, monobasic, nasm, noweb,
    objectivec, objectivecpp, ocaml, octave, opencl, pascal, perl, php, pike,
    postscript, prolog, pure, python, r, relaxng, relaxngcompact, rest, rhtml,
    roff, ruby, rust, scala, scheme, sci, sed, sgml, sql, sqlmysql,
    sqlpostgresql, tcl, tcsh, texinfo, verilog, vhdl, xml, xorg, xslt, xul,
    yacc, yaml, zsh
Default user data directory: /Users/jonas/.pandoc
Copyright (C) 2006-2015 John MacFarlane
Web:  http://johnmacfarlane.net/pandoc
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by fmoralesc** [comment] 2015-06-09 16:24
Thanks.

**Comment by INstinct42** [comment] 2015-06-09 16:30
I think I found the issue:

In file `pythonx/vim_pandoc/command.py` in Line 117:

```python
        return get_raw_pandoc_data("Output formats:(.*)\[\*for pdf")
```
should be
```python
        return get_raw_pandoc_data("Output formats:(.*)\[\*\*for pdf")
```

(Note the extra `\*`)

**Comment by fmoralesc** [comment] 2015-06-09 17:21
OK, just merged the fix into `master`. Does everyone confirm the issue is fixed?

**Comment by zaript** [comment] 2015-06-09 18:15
Works for me with latest MacVim on Yosemite.

**Closed** 2015-06-09 19:07 UTC
Labels: fixed waiting for confirmation

**Comment by nasenatmer** [comment] 2015-06-10 06:48
Wow, what speed! Going to to bed while confirming a bug. Waking up, seeing this solved. Amazing! Thanks a lot!

**Comment by schar** [comment] 2016-10-29 15:37
This issue (or a related one, anyway) seems to have returned. Here is the specific error I'm getting (using pandoc 1.18 and, if it matters, Mac OS 10.12.1). 

```
Error detected while processing function pandoc#command#Pandoc:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/schar/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py
", line 78, in <module>
    class PandocHelpParser(object):
  File "/Users/schar/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py
", line 110, in PandocHelpParser
    @wrap_formats
  File "/Users/schar/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py
", line 75, in wrap_formats
    data = fn()
  File "/Users/schar/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py
", line 112, in _get_input_formats
    return get_raw_pandoc_data("Input formats:(.*)Output formats")
  File "/Users/schar/.vim/bundle/vim-pandoc/pythonx/vim_pandoc/command.py
", line 67, in get_raw_pandoc_data
    return re.search(pattern, data, re.DOTALL).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
line    5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'pandoc' is not defined
```

Changing line `117` as suggested by @joWeiss above does not seem to resolve the issue.

**Comment by redapemusic35** [comment] 2018-11-27 15:16
I am getting a what appears to be related issue: I am currently using Pandoc 2.4, with MacOs High Sierra, gui macvim 8.1.280, 

`Error detected while processing function pandoc#command#Pandoc:
line    5:
Traceback (most recent call last):
  File "/Users/monty/.vim/bundle/vim-pandoc/python3/vim_pandoc/command.py", line 169, in
 execute
    Popen(shlex.split(async_command), stdout=tmp, stderr=tmp)
  File "/usr/local/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shlex.py", lin
e 305, in split
    return list(lex)
  File "/usr/local/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shlex.py", lin
e 295, in __next__
    token = self.get_token()
  File "/usr/local/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shlex.py", lin
e 105, in get_token
    raw = self.read_token()
  File "/usr/local/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shlex.py", lin
e 187, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/monty/.vim/bundle/vim-pandoc/python3/vim_pandoc/command.py", line 141, in
 __call__
    self.execute(should_open)
  File "/Users/monty/.vim/bundle/vim-pandoc/python3/vim_pandoc/command.py", line 171, in
 execute
    vim.command('echoe "vim-pandoc: could not execute pandoc asynchronously"')
vim.error: Vim(echoerr):vim-pandoc: could not execute pandoc asynchronously`
