### ISSUE TITLE
Make disabled folding on split windows optional

### ISSUE THREAD

**Issue by jjaderberg** [vim-pandoc/vim-pandoc#120] opened 2015-02-19 10:12 UTC
The folding module doesn't work with split windows. As I understand it `pandoc#folding#FoldExpr` tests if there are more windows than one open and if so returns without doing any work. There is a code comment stating that this is for performance reasons (it is also stated at the end of the help section for folding). Is it really a big performance problem to maintain folds with split windows? I just started with `vim-pandoc` and possibly am misunderstanding how I am supposed to use it, but so far I have found it limiting to have to choose between splits and folds. Would it be possible to make this performance feature optional? Perhaps a `pandoc#folding#disable_folding_on_splits` option that is checked together with `winnr` before short-circuiting `FoldExpr`. If not, I would suggest explaining the feature a little further and making the information more prominent in the help as I found this folding behavior confusing.

I have tried disabling the three relevant lines of code and have not yet suffered from any tardiness in vim.

**Comment by fmoralesc** [comment] 2015-02-19 10:29
Try opening a split of any pandoc file and type in insert mode. In vim 7.4.617, it makes vim-pandoc unbearably slow. Perhaps some recent change in vim itself is causing this, because I don't remember having this behavior around 7.4.400, but this is consistent for me

This doesn't seem to happen if no other windows point to the pandoc file buffer, so perhaps the test should be more specific. I'm not too keen on making this behaviour optional because if this gets resolved, then the user would have to change his setup to accommodate, and will most likely keep a broken config.

**Comment by jjaderberg** [comment] 2015-02-19 12:03
I see, if this is occasioned by problems in specific versions of vim, which hopefully will be fixed, I understand that you don't want to add configuration based on it. If you decide to make the test more specific and also to let version be a factor, here are my quick findings: using vim-pandoc in MacVim with vim 7.4.258 I can have 8 splits over four different files with ft=pandoc, folding enabled and ranging from 50 to 1500 lines with no ill effects to insertion or normal movement. It's not that it starts to slow down with more splits or larger files, I just haven't tried.

**Comment by fmoralesc** [comment] 2015-02-19 12:17
I think the issue is triggered mostly when the save file is open in several
split windows, which inn my case, it's often. Your vim version might not be
affected by the issue.

**Comment by fmoralesc** [comment] 2015-02-23 01:20
I made it so the folding is disabled only for buffers with multiple splits open, which should improve things.

**Comment by fmoralesc** [comment] 2015-05-21 19:40
Closing for now.

**Closed by fmoralesc** 2015-05-21 19:40 UTC
