### ISSUE TITLE
autocomand in Neovim throws error UnicodeDecodeError('ascii',...

### ISSUE THREAD

**Issue by orrsonn** [vim-pandoc/vim-pandoc#157] opened 2016-02-07 22:31 UTC
Hi.
I am new to pandoc and I am trying to write a technical paper, producing a pdf going through latex. 
I am using Neovim in the newest version on Debian. Using regular vim works.

Following error comes up, when writing a file, which then triggers the autocmd.

```
vim-pandoc:ran:pandoc --latex-engine=pdflatex -o "test.pdf" -s "test.pdc"
"pandoc output" 1L, 24C
Error detected while processing function pandoc#command#JobHandler..provider#python#Call:
line   18:
UnicodeDecodeError('ascii', '\xe2\x96\xb6 ', 0, 1, 'ordinal not in range(128)')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/neovim/msgpack_rpc/session.py", line 177, in handler
    rv = self._request_cb(name, args)
  File "/usr/local/lib/python2.7/dist-packages/neovim/api/common.py", line 237, in filter_request_cb
    walk(self._in, args, self, name, 'request'))
  File "/usr/local/lib/python2.7/dist-packages/neovim/plugin/host.py", line 65, in _on_request
    rv = handler(*args)
  File "/usr/share/nvim/runtime/autoload/provider/script_host.py", line 77, in python_execute
    exec(script, self.module.__dict__)
  File "<string>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
Error detected while processing function pandoc#command#JobHandler..provider#python#Call:
```

I set following in my vimrc
```
let g:pandoc#command#latex_engine = 'pdflatex'
let g:pandoc#command#autoexec_on_writes = '1'
let g:pandoc#command#autoexec_command = 'Pandoc pdf -s'
```

This error came also when runing manually without setting pdflatex as an engine.
Running manually works now.

**Comment by fmoralesc** [comment] 2016-02-08 00:18
It was due to a difference in the python interpreter behavior, please check if it's fixed in the latest commit.

**Comment by orrsonn** [comment] 2016-02-11 00:56
I am still getting the same error =/

**Comment by fmoralesc** [comment] 2016-02-11 12:13
Are you using the python2 or python3 host in neovim?

**Comment by fmoralesc** [comment] 2016-02-11 12:15
Sorry, I should have paid more attention. python2 it is, let me see...

**Comment by orrsonn** [comment] 2016-02-11 12:42
I have both python2 and python3 host installed and I guess vim-pandoc automatically uses python2 in this case?!

**Comment by fmoralesc** [comment] 2016-02-11 12:47
Yes, it does. I found another issue  using python3, but all of this seems to be coming from python-neovim itself... Using python2, however, I can no longer reproduce the issue. Is there anything special in your locale, or the paths you are using the plugin from. The python plugin seems to be choking in some input...

**Comment by orrsonn** [comment] 2016-02-12 18:53
It seams to work the very first time and then always the same error. (closing the file and reopening doesn't work either)
creating my own autocmd doesn't work either: ```autocmd BufWrite *.pdc :Pandoc pdf -s```
running the same command manually works. => i maped it to a hotkey and that works for now

**Comment by orrsonn** [comment] 2016-02-12 22:23
BuffWritePost was the key :)

**Closed** 2016-02-12 22:25 UTC
