### ISSUE TITLE
<C-CR> does not keep TOC open (nor does it close it, if behaviour is reversed)

### ISSUE THREAD

**Issue by SuperFluffy** [vim-pandoc/vim-pandoc#131] opened 2015-05-28 10:23 UTC
When opening the table of contents buffer in a new window with `:TOC`, navigating to a link and hitting `<C-CR>` (control + carriage return), `vim` still closes the TOC window.

Equivalently, after setting `:let g:pandoc#toc#close_after_navigating = 0`, the window is now *not* closed after pressing `<C-CR>`.

`vim` version: `7.4.729`
`vim-pandoc` version: Latest `git`

**Comment by fmoralesc** [comment] 2015-06-02 15:20
Just pushed a fix. Please confirm.

**Comment by SuperFluffy** [comment] 2015-06-03 13:49
Still doesn't run on my machine. `<C-CR>` doesn't keep it open (in the case of `g:pandoc#toc#close_after_navigating = 1`), nor does it close the window (in the case of `= 0`). I will try on my machine at home tonight as well.

**Comment by fmoralesc** [comment] 2015-06-03 14:49
Please give me the output of `:map <buffer>` when the TOC is open. Perhaps something is interfering.

**Comment by SuperFluffy** [comment] 2015-06-03 15:25
This is the output with `TOC` open:
```
   <CR>        *@g:pandoc#toc#close_after_navigating == 1 ? '<CR>:lclose<CR>' : '<CR>'
   q           *@:lclose<CR>
   <C-CR>      *@g:pandoc#toc#close_after_navigating == 1 ? '<CR>': '<CR>:lclose<CR>'
```

**Comment by fmoralesc** [comment] 2015-06-03 15:36
That output means it was registered... Hm, will inspect further, please wait some.

**Comment by fmoralesc** [comment] 2015-06-22 01:54
At this date, I can't reproduce, and the behaviuor seems fine in my setup. Closing.

**Closed by fmoralesc** 2015-06-22 01:54 UTC

**Comment by joelostblom** [comment] 2020-02-01 13:33
For future reference, this might be an issue with the terminal not being able to distinguish between enter with and without control. This can be tested by pressing `Ctrl` + `v` in insert mode followed by either enter or control enter and see if the register as the same symbol. Details here https://stackoverflow.com/questions/598113/can-terminals-detect-shift-enter-or-control-enter
